import { GoogleGenAI, Modality, GenerateContentResponse } from "@google/genai";

const getAI = () => {
    // Return null if no key to trigger catch blocks immediately
    if (!process.env.API_KEY || process.env.API_KEY === 'undefined') return null;
    return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

// --- MOCK DATA GENERATORS (Untuk Mode Tanpa API Key) ---

const getMockAdminContent = (prompt: string) => {
    return `
    <div style="font-family: 'Times New Roman', serif; color: #000000;">
        <h1 style="text-align:center;">Dokumen Administrasi Guru (Mode Simulasi)</h1>
        <h3 style="text-align:center;">Tahun Ajaran 2025/2026</h3>
        <hr style="border: 2px solid black; margin: 20px 0;">
        
        <h2 style="text-align:center;">Modul Ajar / Rencana Pelaksanaan Pembelajaran</h2>
        <table style="width:100%; border-collapse:collapse; border:1px solid black; margin-bottom: 20px;">
            <tr>
                <th style="background-color:#f0f0f0; border:1px solid black; padding:8px; width: 30%;">Informasi Umum</th>
                <td style="border:1px solid black; padding:8px;">Generated by GenGuru (Simulation)</td>
            </tr>
            <tr>
                <th style="background-color:#f0f0f0; border:1px solid black; padding:8px;">Mata Pelajaran</th>
                <td style="border:1px solid black; padding:8px;">Sesuai Input Pengguna</td>
            </tr>
            <tr>
                <th style="background-color:#f0f0f0; border:1px solid black; padding:8px;">Tahun Ajaran</th>
                <td style="border:1px solid black; padding:8px;">2025/2026</td>
            </tr>
            <tr>
                <th style="background-color:#f0f0f0; border:1px solid black; padding:8px;">Fase / Kelas</th>
                <td style="border:1px solid black; padding:8px;">Fase E / Kelas 10</td>
            </tr>
            <tr>
                <th style="background-color:#f0f0f0; border:1px solid black; padding:8px;">Alokasi Waktu</th>
                <td style="border:1px solid black; padding:8px;">2 x 45 Menit</td>
            </tr>
        </table>

        <h3>A. Tujuan Pembelajaran</h3>
        <ul>
            <li>Peserta didik mampu memahami konsep dasar materi.</li>
            <li>Peserta didik mampu menganalisis permasalahan terkait topik.</li>
            <li>Peserta didik mampu mempresentasikan hasil diskusi kelompok.</li>
        </ul>

        <h3>B. Kegiatan Pembelajaran</h3>
        <table style="width:100%; border-collapse:collapse; border:1px solid black;">
            <tr style="background-color:#f0f0f0;">
                <th style="border:1px solid black; padding:8px;">Tahapan</th>
                <th style="border:1px solid black; padding:8px;">Kegiatan Guru & Siswa</th>
                <th style="border:1px solid black; padding:8px;">Waktu</th>
            </tr>
            <tr>
                <td style="border:1px solid black; padding:8px;">Pendahuluan</td>
                <td style="border:1px solid black; padding:8px;">Guru membuka salam, berdoa, dan absensi. Apersepsi materi sebelumnya.</td>
                <td style="border:1px solid black; padding:8px;">10 Menit</td>
            </tr>
            <tr>
                <td style="border:1px solid black; padding:8px;">Inti</td>
                <td style="border:1px solid black; padding:8px;">
                    1. <strong>Stimulation:</strong> Guru menyajikan masalah.<br>
                    2. <strong>Problem Statement:</strong> Siswa mengidentifikasi masalah.<br>
                    3. <strong>Data Collection:</strong> Diskusi kelompok.<br>
                    4. <strong>Verification:</strong> Presentasi hasil.
                </td>
                <td style="border:1px solid black; padding:8px;">70 Menit</td>
            </tr>
            <tr>
                <td style="border:1px solid black; padding:8px;">Penutup</td>
                <td style="border:1px solid black; padding:8px;">Refleksi, kesimpulan, dan doa penutup.</td>
                <td style="border:1px solid black; padding:8px;">10 Menit</td>
            </tr>
        </table>
        <br>
        <p><em>Catatan: Ini adalah konten simulasi karena API Key tidak terdeteksi. Dalam mode produksi dengan API Key, konten akan digenerate secara spesifik sesuai prompt AI.</em></p>
    </div>
    `;
};

const getMockQuestionContent = (prompt: string) => {
    return `
    <div style="font-family: 'Times New Roman', serif; color: #000000;">
        <!-- 1. HEADER AL-GHOZALI -->
        <div style="border: 1px solid black; padding: 0; margin-bottom: 20px;">
            <table style="width: 100%; border-collapse: collapse; border: none;">
                <tr style="border-bottom: 1px solid black;">
                    <td style="width: 20%; text-align: center; padding: 10px; border-right: 1px solid black; border-left: none; border-top: none;">
                       <img src="https://upload.wikimedia.org/wikipedia/commons/2/27/Logo_YPI_Al-Ghozali.png" alt="Logo" width="90" height="90" style="display:block; margin:auto;">
                       <br><span style="font-size:10px;">YPI AL-GHOZALI</span>
                    </td>
                    <td style="width: 80%; text-align: center; padding: 5px; border: none;">
                        <h3 style="margin:0; font-size: 14pt; font-weight: normal;">YAYASAN PENDIDIKAN ISLAM PONDOK MODERN AL-GHOZALI</h3>
                        <h2 style="margin:5px 0; font-size: 18pt; font-weight: bold;">SMA ISLAM AL-GHOZALI</h2>
                        <p style="margin:0; font-size: 10pt;">Telp. (0251) 8614072, e-mail: smaislamalghozalisma@ymail.com</p>
                    </td>
                </tr>
            </table>
            <div style="text-align: center; border-bottom: 1px solid black; padding: 8px; background-color: #fff;">
                <h3 style="margin: 0; font-size: 14pt; font-weight: bold; letter-spacing: 1px;">PENILAIAN SUMATIF AKHIR SEMESTER GANJIL</h3>
                <h4 style="margin: 5px 0 0 0; font-size: 12pt; font-weight: bold;">TAHUN PELAJARAN 2025-2026</h4>
            </div>
            <div style="padding: 10px;">
                <table style="width: 100%; font-size: 12pt; border: none;">
                    <tr>
                        <td style="width: 15%; font-weight: bold; border: none;">Mata Pelajaran</td>
                        <td style="width: 35%; border: none;">: (Mode Simulasi)</td>
                        <td style="width: 15%; font-weight: bold; border: none;">Hari/Tanggal</td>
                        <td style="width: 35%; border: none;">: ....................................</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold; border: none;">Kelas</td>
                        <td style="border: none;">: X (Sepuluh)</td>
                        <td style="font-weight: bold; border: none;">Jam Ke-</td>
                        <td style="border: none;">: ....................................</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold; border: none;">Waktu</td>
                        <td style="border: none;">: 90 Menit</td>
                        <td style="border: none;"></td>
                        <td style="border: none;"></td>
                    </tr>
                </table>
            </div>
        </div>

        <!-- 1. NASKAH SOAL -->
        <h3>I. NASKAH SOAL</h3>
        <h4>A. PILIHAN GANDA</h4>
        <p><em>Berilah tanda silang (X) pada huruf A, B, C, D, atau E pada jawaban yang benar!</em></p>
        <ol>
            <li>
                Sosiologi disebut sebagai ilmu pengetahuan yang empiris karena didasarkan pada...
                <ol type="A" style="list-style-type: upper-alpha;">
                    <li>Pemikiran logis dan akal sehat</li>
                    <li>Keyakinan masyarakat</li>
                    <li><strong>Observasi terhadap kenyataan dan tidak spekulatif</strong></li>
                    <li>Data statistik kependudukan</li>
                    <li>Teori masa lalu</li>
                </ol>
            </li>
            <br>
            <li>
                Perhatikan pernyataan berikut! (1) Perubahan iklim, (2) Kemiskinan di kota besar. Manakah yang termasuk objek kajian sosiologi?
                <ol type="A" style="list-style-type: upper-alpha;">
                    <li>Hanya (1)</li>
                    <li><strong>Hanya (2) karena berkaitan dengan masalah sosial</strong></li>
                    <li>Keduanya benar</li>
                    <li>Keduanya salah</li>
                    <li>Semua jawaban ragu-ragu</li>
                </ol>
            </li>
        </ol>

        <h4>B. URAIAN</h4>
        <ol>
            <li>Jelaskan fungsi Sosiologi dalam perencanaan sosial!</li>
            <li>Sebutkan 3 ciri-ciri sosiologi sebagai ilmu pengetahuan!</li>
        </ol>

        <hr style="border: 2px solid black; margin: 30px 0;">

        <!-- 2. KISI-KISI SOAL -->
        <h3>II. KISI-KISI PENULISAN SOAL</h3>
        <table style="width:100%; border-collapse:collapse; border:1px solid black;">
            <tr style="background-color:#f0f0f0;">
                <th style="border:1px solid black;">No</th>
                <th style="border:1px solid black;">Kompetensi Dasar</th>
                <th style="border:1px solid black;">Materi</th>
                <th style="border:1px solid black;">Indikator Soal</th>
                <th style="border:1px solid black;">Level Kognitif</th>
                <th style="border:1px solid black;">No Soal</th>
            </tr>
            <tr>
                <td style="border:1px solid black; text-align:center;">1</td>
                <td style="border:1px solid black;">Memahami pengetahuan dasar Sosiologi</td>
                <td style="border:1px solid black;">Konsep Dasar</td>
                <td style="border:1px solid black;">Siswa dapat menjelaskan sifat empiris sosiologi</td>
                <td style="border:1px solid black;">L1 (Pengetahuan)</td>
                <td style="border:1px solid black; text-align:center;">1</td>
            </tr>
        </table>

        <br>

        <!-- 3. KUNCI JAWABAN & PEMBAHASAN -->
        <h3>III. KUNCI JAWABAN & PEMBAHASAN</h3>
        <table style="width:100%; border-collapse:collapse; border:1px solid black;">
            <tr style="background-color:#f0f0f0;">
                <th style="border:1px solid black;">No</th>
                <th style="border:1px solid black;">Kunci</th>
                <th style="border:1px solid black;">Pembahasan Singkat</th>
                <th style="border:1px solid black;">Skor</th>
            </tr>
            <tr>
                <td style="border:1px solid black; text-align:center;">1</td>
                <td style="border:1px solid black; text-align:center;">C</td>
                <td style="border:1px solid black;">Sosiologi bersifat empiris artinya berdasarkan observasi, bukan spekulasi.</td>
                <td style="border:1px solid black; text-align:center;">10</td>
            </tr>
        </table>

        <br>

        <!-- 4. ANALISIS SOAL KUALITATIF -->
        <h3>IV. ANALISIS SOAL KUALITATIF</h3>
        <table style="width:100%; border-collapse:collapse; border:1px solid black;">
             <tr style="background-color:#f0f0f0;">
                <th style="border:1px solid black;">Aspek Penelaahan</th>
                <th style="border:1px solid black;">Hasil Analisis</th>
            </tr>
            <tr>
                <td style="border:1px solid black;">Materi</td>
                <td style="border:1px solid black;">Soal sesuai dengan indikator dan kurikulum yang berlaku.</td>
            </tr>
            <tr>
                <td style="border:1px solid black;">Konstruksi</td>
                <td style="border:1px solid black;">Pokok soal dirumuskan dengan jelas dan tegas.</td>
            </tr>
            <tr>
                <td style="border:1px solid black;">Bahasa</td>
                <td style="border:1px solid black;">Menggunakan bahasa Indonesia yang baku dan komunikatif.</td>
            </tr>
        </table>

        <br>

        <!-- 5. RUBRIK PENILAIAN -->
        <h3>V. RUBRIK PENILAIAN / PENSKORAN</h3>
        <p><strong>Rumus Nilai Akhir:</strong></p>
        <p>Nilai = (Jumlah Skor Perolehan / Jumlah Skor Maksimal) x 100</p>
        <ul>
            <li>Pilihan Ganda: Benar = 1, Salah = 0</li>
            <li>Uraian:
                <ul>
                    <li>Skor 4: Jawaban lengkap dan benar sempurna.</li>
                    <li>Skor 3: Jawaban benar tetapi kurang lengkap.</li>
                    <li>Skor 2: Jawaban kurang tepat.</li>
                    <li>Skor 1: Menjawab tetapi salah.</li>
                </ul>
            </li>
        </ul>

        <br>

        <!-- 6. RINGKASAN MATERI -->
        <h3>VI. RINGKASAN MATERI</h3>
        <p>Sosiologi adalah ilmu yang mempelajari masyarakat, interaksi sosial, dan pola-pola hubungan antar manusia. Ciri-ciri sosiologi antara lain:</p>
        <ol>
            <li><strong>Empiris:</strong> Berdasarkan observasi.</li>
            <li><strong>Teoritis:</strong> Menyusun abstraksi dari hasil observasi.</li>
            <li><strong>Kumulatif:</strong> Teori disusun berdasarkan teori yang sudah ada.</li>
            <li><strong>Non-Etis:</strong> Tidak menilai baik buruknya fakta.</li>
        </ol>
    </div>
    `;
};

const getMockPesantrenContent = (prompt: string) => {
    return `
    <div dir="rtl" style="font-family: 'Traditional Arabic', serif; font-size: 18px; color: #000000;">
        <h2 style="text-align:center;">مَعْهَدُ الْغَزَالِي الْعَصْرِيِّ</h2>
        <h3 style="text-align:center;">الِامْتِحَانُ التَّحْرِيْرِيُّ (SIMULASI)</h3>
        <p style="text-align:center;">السَّنَةُ الدِّرَاسِيَّةُ : ٢٠٢٥/٢٠٢٦ م</p>
        <hr style="border: 1px solid black;">
        
        <table style="width:100%; border-collapse:collapse; border:1px solid black; direction:rtl;">
            <tr>
                <td style="border:1px solid black; padding:5px;">الْمَادَّةُ : النَّحْوُ / الْفِقْهُ</td>
                <td style="border:1px solid black; padding:5px;">الْفَصْلُ : الْأَوَّلُ</td>
            </tr>
        </table>
        <br>

        <h3>أ. الْمُفْرَدَاتُ (Al-Mufradat)</h3>
        <p>أَكْمِلِ الْجُمَلَ الْآتِيَةَ بِالْكَلِمَةِ الْمُنَاسِبَةِ:</p>
        <ol>
            <li>ذَهَبَ أَحْمَدُ إِلَى ......... لِطَلَبِ الْعِلْمِ. (الْمَدْرَسَةِ / السُّوْقِ)</li>
            <li>......... التِّلْمِيْذُ الْقُرْآنَ فِي الْمَسْجِدِ. (قَرَأَ / نَامَ)</li>
        </ol>

        <h3>ب. التَّرَاكِيْبُ (At-Tarakib)</h3>
        <p>رَتِّبِ الْكَلِمَاتِ الْآتِيَةَ لِتَكُوْنَ جُمْلَةً مُفِيْدَةً:</p>
        <ol>
            <li>( الْمَسْجِدِ - فِي - صَلَّى - الْمُسْلِمُ )</li>
            <li>( الْكِتَابَ - عَلَى - وَضَعَ - الْمَكْتَبِ - مُحَمَّدٌ )</li>
        </ol>

        <h3>ج. الْقَوَاعِدُ (Al-Qawaid)</h3>
        <p>أَعْرِبْ مَا تَحْتَهُ خَطٌّ:</p>
        <ul>
            <li><u>الْعِلْمُ</u> نُوْرٌ.</li>
            <li>ضَرَبَ <u>زَيْدٌ</u> عَمْرًا.</li>
        </ul>
    </div>
    `;
};

// --- MAIN SERVICES ---

export const generateTextContent = async (prompt: string, systemInstruction?: string) => {
  try {
    const ai = getAI();
    if (!ai) throw new Error("No API Key");

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.7,
      }
    });
    return response.text;
  } catch (error) {
    console.warn("AI Key missing or error, using mock data.", error);
    // Fallback logic
    if (prompt.includes("Administrasi") || prompt.includes("Modul Ajar")) return getMockAdminContent(prompt);
    if (prompt.includes("Pesantren") || prompt.includes("Bahasa Arab")) return getMockPesantrenContent(prompt);
    if (prompt.includes("Soal")) return getMockQuestionContent(prompt);
    return "<p>Mode Simulasi: Konten berhasil dibuat. Harap masukkan API Key untuk hasil AI yang sebenarnya.</p>";
  }
};

// New function for Streaming response
export const generateTextContentStream = async (
    prompt: string, 
    onChunk: (text: string) => void,
    systemInstruction?: string
): Promise<string> => {
    try {
        const ai = getAI();
        if (!ai) throw new Error("No API Key");

        const responseStream = await ai.models.generateContentStream({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                systemInstruction: systemInstruction,
                temperature: 0.7,
            }
        });

        let fullText = '';
        for await (const chunk of responseStream) {
            const chunkText = (chunk as GenerateContentResponse).text || '';
            fullText += chunkText;
            onChunk(chunkText);
        }
        return fullText;
    } catch (error) {
        console.warn("AI Stream Error/Missing Key, simulating stream...", error);
        
        // Mock Stream Logic
        let content = "";
        if (prompt.toLowerCase().includes("administrasi")) content = getMockAdminContent(prompt);
        else if (prompt.toLowerCase().includes("pesantren")) content = getMockPesantrenContent(prompt);
        else if (prompt.toLowerCase().includes("soal") || prompt.toLowerCase().includes("paket asesmen")) content = getMockQuestionContent(prompt);
        else content = getMockAdminContent(prompt);

        // Simulate typing effect
        const chunkSize = 50; // Faster chunk for better UX in mock
        let currentPos = 0;
        
        return new Promise((resolve) => {
            const interval = setInterval(() => {
                const nextChunk = content.slice(currentPos, currentPos + chunkSize);
                onChunk(nextChunk);
                currentPos += chunkSize;
                
                if (currentPos >= content.length) {
                    clearInterval(interval);
                    resolve(content);
                }
            }, 20); // Speed of simulation
        });
    }
};

export const generateImage = async (prompt: string): Promise<string | null> => {
  try {
    const ai = getAI();
    if (!ai) throw new Error("No API Key");

    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: '1:1',
      },
    });
    const base64ImageBytes = response.generatedImages?.[0]?.image?.imageBytes;
    if (base64ImageBytes) {
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    }
    return null;
  } catch (error) {
    console.warn("Image gen error/missing key, using placeholder.");
    // Return a dynamic placeholder image based on text
    const encodedText = encodeURIComponent(prompt.substring(0, 20));
    return `https://placehold.co/600x600/1e293b/FFF?text=${encodedText}`;
  }
};

export const generateVideo = async (prompt: string): Promise<string | undefined> => {
  try {
    const ai = getAI();
    if (!ai) throw new Error("No API Key");
    
    // Check API key selection for Veo if using real AI
    if (window.aistudio && !await window.aistudio.hasSelectedApiKey()) {
        await window.aistudio.openSelectKey();
    }
    
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: prompt,
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: '16:9'
      }
    });

    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 5000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (downloadLink) {
        return `${downloadLink}&key=${process.env.API_KEY}`;
    }
    return undefined;
  } catch (error) {
    console.warn("Video gen error/missing key, using sample.");
    // Return a sample video URL (Creative Commons)
    return "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4";
  }
};

export const textToSpeech = async (text: string, voiceName: string = 'Kore'): Promise<ArrayBuffer | null> => {
    try {
        const ai = getAI();
        if (!ai) throw new Error("No API Key");

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-preview-tts",
            contents: [{ parts: [{ text: text }] }],
            config: {
                responseModalities: [Modality.AUDIO],
                speechConfig: {
                    voiceConfig: {
                        prebuiltVoiceConfig: { voiceName: voiceName },
                    },
                },
            },
        });

        const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
        if (base64Audio) {
             const binaryString = atob(base64Audio);
             const len = binaryString.length;
             const bytes = new Uint8Array(len);
             for (let i = 0; i < len; i++) {
                bytes[i] = binaryString.charCodeAt(i);
             }
             return bytes.buffer;
        }
        return null;

    } catch (e) {
        console.warn("TTS Error/No Key", e);
        return null; // Return null so the UI can fallback to Browser TTS
    }
}

export const editImage = async (base64Image: string, prompt: string): Promise<string | null> => {
    try {
        const ai = getAI();
        if (!ai) throw new Error("No API Key");

        const data = base64Image.replace(/^data:image\/(png|jpeg|jpg);base64,/, "");
        
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: data,
                            mimeType: 'image/png',
                        },
                    },
                    { text: prompt },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        const part = response.candidates?.[0]?.content?.parts?.[0];
        if (part && part.inlineData) {
             return `data:image/png;base64,${part.inlineData.data}`;
        }
        return null;
    } catch(e) {
        console.warn("Edit Image Error, returning original");
        return base64Image; // Fallback: return original image
    }
}